package org.denigma.nlp.pubmed

case class EntrezDatabase(name: String, UID: String, eUtility_Name: String)

object EntrezDatabase {
  val BioProject = EntrezDatabase("BioProject", "BioProject ID", "bioproject")
  val BioSample = EntrezDatabase("BioSample", "BioSample ID", "biosample")
  val Biosystems = EntrezDatabase("Biosystems", "BSID", "biosystems")
  val Books = EntrezDatabase("Books", "Book ID", "books")
  val ConservedDomains = EntrezDatabase("Conserved Domains", "PSSM-ID", "cdd")
  val DbGaP = EntrezDatabase("dbGaP", "dbGaP ID", "gap")
  val DbVar = EntrezDatabase("dbVar", "dbVar ID", "dbvar")
  val Epigenomics = EntrezDatabase("Epigenomics", "Epigenomics ID", "epigenomics")
  val EST = EntrezDatabase("EST", "GI number", "nucest")
  val Gene = EntrezDatabase("Gene", "Gene ID", "gene")
  val Genome = EntrezDatabase("Genome", "Genome ID", "genome")
  val GEODatasets = EntrezDatabase("GEO Datasets", "GDS ID", "gds")
  val GEOProfiles = EntrezDatabase("GEO Profiles", "GEO ID", "geoprofiles")
  val GSS = EntrezDatabase("GSS", "GI number", "nucgss")
  val HomoloGene = EntrezDatabase("HomoloGene", "HomoloGene ID", "homologene")
  val MeSH = EntrezDatabase("MeSH", "MeSH ID", "mesh")
  val NCBI_Cpp = EntrezDatabase("NCBI C++ Toolkit", "Toolkit ID", "toolkit")
  val NCBI_Web_Site = EntrezDatabase("NCBI Web Site", "Web Site ID", "ncbisearch")
  val NLM_Catalog = EntrezDatabase("NLM Catalog", "NLM Catalog ID", "nlmcatalog")
  val Nucleotide = EntrezDatabase("Nucleotide", "GI number", "nuccore")
  val OMIA = EntrezDatabase("OMIA", "OMIA ID", "omia")
  val PopSet = EntrezDatabase("PopSet", "PopSet ID", "popset")
  val Probe = EntrezDatabase("Probe", "Probe ID", "probe")
  val Protein = EntrezDatabase("Protein GI", "number", "protein")
  val ProteinClusters = EntrezDatabase("Protein Clusters", "Protein Cluster ID", "proteinclusters")
  val PubChemBioAssay = EntrezDatabase("PubChem BioAssay", "AID", "pcassay")
  val PubChemCompound = EntrezDatabase("PubChem Compound", "CID", "pccompound")
  val PubChemSubstance = EntrezDatabase("PubChem Substance", "SID", "pcsubstance")
  val PubMed = EntrezDatabase("PubMed", "PMID", "pubmed")
  val PubMedCentral = EntrezDatabase("PubMed Central", "PMCID", "pmc")
  val SNP = EntrezDatabase("SNP", "rs number", "snp")
  val SRA = EntrezDatabase("SRA", "SRA ID", "sra")
  val Structure = EntrezDatabase("Structure", "MMDB-ID", "structure")
  val Taxonomy = EntrezDatabase("Taxonomy", "TaxID", "taxonomy")
  val UniGene = EntrezDatabase("UniGene", "UniGene Cluster ID", "unigene")
  val UniSTS = EntrezDatabase("UniSTS", "STS ID", "unists")
}